package domain;
// Generated Apr 19, 2023, 11:51:42 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lop generated by hbm2java
 */
@Entity
@Table(name = "lop", catalog = "qlsv")
public class Lop implements java.io.Serializable {

	private int malop;
	private String tenlop;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lop")
	private Set<Sinhvien> sinhviens = new HashSet<Sinhvien>(0);

	public Lop() {
	}

	public Lop(int malop) {
		this.malop = malop;
	}

	public Lop(int malop, String tenlop, Set<Sinhvien> sinhviens) {
		this.malop = malop;
		this.tenlop = tenlop;
		this.sinhviens = sinhviens;
	}

	@Id

	@Column(name = "malop", unique = true, nullable = false)
	public int getMalop() {
		return this.malop;
	}

	public void setMalop(int malop) {
		this.malop = malop;
	}

	@Column(name = "tenlop", length = 50)
	public String getTenlop() {
		return this.tenlop;
	}

	@Override
	public String toString() {
		return "Lop [tenlop=" + tenlop + "]";
	}

	public void setTenlop(String tenlop) {
		this.tenlop = tenlop;
	}

	
	public Set<Sinhvien> getSinhviens() {
		return this.sinhviens;
	}

	public void setSinhviens(Set<Sinhvien> sinhviens) {
		this.sinhviens = sinhviens;
	}

}
